services:
  database:
    container_name: colormagic_database
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: colormagic
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27018:27017"
    restart: always
